.catalog:
  name: "Mysql"
  version: "5.10.6"
  description: "Database"
  questions:
    - variable: "context_path"
      label: "Context path"
      description: |
        The context path under which Confluence will be available
      type: "string"
      default: "/confluence"
      required: false
  
