name: fluxday
description: OPENSOURCE TASK & PRODUCTIVITY MANAGEMENT TOOL FOR STARTUPS
version: 0
category: Productivity
maintainer: Matthieu CONGY
license: Apache License 2.0
projectURL: http://fluxday.io/
