language: python
python:
  - "3.4"
  - "3.5"
services:
  - rabbitmq # will start rabbitmq-server
cache:
  - apt
  - pip
before_install:
  - sudo apt-get -qq update
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get install -y postgresql-9.4
  - sudo apt-get install -y postgresql-plpython-9.4
  - sudo /etc/init.d/postgresql start 9.4
  - psql -c 'create database taiga;' -U postgres
install:
  - travis_retry pip install -r requirements-devel.txt
script:
  - travis_retry coverage run --source=taiga --omit='*tests*,*commands*,*migrations*,*admin*,*.jinja,*dashboard*,*settings*,*wsgi*,*questions*,*documents*' -m py.test -v --tb=native
after_success:
  - coveralls
